#!/bin/bash

echo ""
echo "╔══════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                          ║"
echo "║           🚀 ONCREATORS - STARTUP SCRIPT 🚀                             ║"
echo "║                                                                          ║"
echo "║         Starting the Creator Marketplace Platform                        ║"
echo "║                                                                          ║"
echo "╚══════════════════════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}Step 1: Starting Docker containers...${NC}"
echo ""
docker-compose up -d

echo ""
echo -e "${BLUE}Step 2: Waiting for services to initialize...${NC}"
sleep 15

echo ""
echo -e "${BLUE}Step 3: Running database migrations...${NC}"
npm run db:migrate

echo ""
echo -e "${GREEN}✅ ALL SERVICES STARTED!${NC}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${GREEN}🌐 ONCREATORS IS NOW RUNNING!${NC}"
echo ""
echo "Access the platform:"
echo ""
echo "  📱 Frontend (React):       ${BLUE}http://localhost:3000${NC}"
echo "  🔌 Backend API (NestJS):   ${BLUE}http://localhost:3333${NC}"
echo "  📚 API Documentation:      ${BLUE}http://localhost:3333/docs${NC}"
echo "  🗄️  Database Management:    ${BLUE}http://localhost:5050${NC}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Test Accounts:"
echo ""
echo -e "${YELLOW}ADMIN (Full Access):${NC}"
echo "  Email:    admin@oncreators.com"
echo "  Password: Admin@123456"
echo ""
echo -e "${YELLOW}CREATOR (Content Creator):${NC}"
echo "  Email:    creator@oncreators.com"
echo "  Password: Creator@123456"
echo ""
echo -e "${YELLOW}USER (Regular User):${NC}"
echo "  Email:    user@oncreators.com"
echo "  Password: User@123456"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Test Payment (Stripe):"
echo ""
echo "  Card Number: 4242 4242 4242 4242"
echo "  Expiry:      12/25"
echo "  CVC:         123"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "What You Can Do:"
echo ""
echo "  ✅ Sign up and create an account"
echo "  ✅ Browse creators on the platform"
echo "  ✅ View creator profiles and ratings"
echo "  ✅ Subscribe to Premium or VIP plans"
echo "  ✅ Make test payments (Stripe test mode)"
echo "  ✅ View your profile and watch history"
echo "  ✅ Access admin dashboard (/admin)"
echo "  ✅ View creator earnings and analytics"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Container Status:"
echo ""
docker-compose ps
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "To stop all services:"
echo ""
echo "  ${YELLOW}docker-compose down${NC}"
echo ""
echo "To view logs:"
echo ""
echo "  ${YELLOW}docker-compose logs -f${NC}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${GREEN}🎬 OnCreators is ready to use! Open http://localhost:3000 in your browser.${NC}"
echo ""
echo "Happy exploring! 🚀"
echo ""
